### ISSUE TITLE
Parse logs

### ISSUE THREAD

**Issue by thesattiraju** [shigupt202/local-container-scan#15]
![image](https://user-images.githubusercontent.com/25762922/77348075-d8361d80-6d5e-11ea-989d-1fabb8d9230e.png)

In case of this, we need to figure out the reason and mount it to the errors section for the action perhaps? Cause if we make it silent/move it to the job (on service side) is there any other way to bring up these details?

**Comment by thesattiraju** [comment]
This seems like a weird error from dockle. When is this expected?
 
![image](https://user-images.githubusercontent.com/25762922/77348306-39f68780-6d5f-11ea-8a54-1d0895425481.png)

**Comment by thesattiraju** [comment]
Add some extra `[INFO]` logs. Like `Scan started...` `Scan complete...`

**Comment by shigupt202** [comment]
Removing extra Trivy logs by running it silently. Also, added extra console logs. Here's the [PR](https://github.com/shigupt202/local-container-scan/pull/17) for it.
