### ISSUE TITLE
Whitelisted vulnerabilities for CIS checks are shown on check run page

### ISSUE THREAD

**Issue by shigupt202** [shigupt202/local-container-scan#16]
Dockle shows all the vulnerabilities in the output logs, even the ones which are whitelisted (The whitelisted vulnerabilities are marked with level "IGNORE"). However, in the code we are simply parsing through all the vulnerabilities without checking the level, and that's why we see the whitelisted vulnerabilities in the check-run description page.
![image](https://user-images.githubusercontent.com/57620559/77391307-760d0500-6dbe-11ea-841e-cdc3f603aacf.png)

**Comment by ajinkya599** [comment]
Should be fixed.
Dockle summary (as returned by Dockle) seems to contain the ignored ones too :/ Not sure what we can do for that.
<img width="526" alt="image" src="https://user-images.githubusercontent.com/11447401/77414095-7a4d1880-6de6-11ea-9941-7417a78b08fa.png">

**Comment by thesattiraju** [comment]
Build up the summary section logic within action and don't print ignored ones

**Comment by ajinkya599** [comment]
> Build up the summary section logic within action and don't print ignored ones

Upon testing again, summary doesn't include the ignored ones (I misspelled in the whitelist file which led to the mis-understanding). Using Dockle summary with selective nodes (info, warn, fatal)
