### ISSUE TITLE
In Trivy output, there are duplicate CVE's.

### ISSUE THREAD

**Issue by ajinkya599** [shigupt202/local-container-scan#18]
I believe Trivy reports vulnerability along with different packages. That's why there are repetitions.

So, if we are not adding packages as a part of check run details, we should filter out the duplicates.
For the logs, we should do the same.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/11447401/77409340-1410c780-6ddf-11ea-92d7-b8c72f54e390.png">

**Comment by thesattiraju** [comment]
Make the CVEs clickable in the details section if a source link is available.

**Comment by ajinkya599** [comment]
> Make the CVEs clickable in the details section if a source link is available.

Removed duplicates.
Not making clickable because of space crunch as found in spike - #19.
