### ISSUE TITLE
SPIKE: Test the hard limits of check run details

### ISSUE THREAD

**Issue by thesattiraju** [shigupt202/local-container-scan#19]

**Comment by ajinkya599** [comment]
The supported text size is **`65535`** characters :
<img width="770" alt="image" src="https://user-images.githubusercontent.com/11447401/77427881-2d287100-6dfd-11ea-821c-59bc24068207.png">

I am in favour of keeping the check-run details as concise as possible. Add any extra details to the logs.
Title itself seems to contain average **`100`** characters. This would mean a limit of less than 600 CVEs (if we post "ID, Title") which seems pretty low.

@ammohant @ds-ms @shigupt202 - Thoughts?

**Comment by shigupt202** [comment]
I would prefer that we keep the details in the logs, and have hyperlinks on CVE's on the check run page.

**Comment by ajinkya599** [comment]
Agreed that hyperlink would have been useful, but space problem exists for hyperlink as well. A typical URL seems to be 60-80 characters long. A similar argument as above holds true.

**Comment by thesattiraju** [comment]
True. But the details page isn't exactly useful for the user either. 
How about in details we just dump the CVEs in a whitelist YAML format and ask them to append it to their whitelist to file, if they need it?

**Comment by ammohant** [comment]
> The supported text size is **`65535`** characters :
> <img alt="image" width="770" src="https://user-images.githubusercontent.com/11447401/77427881-2d287100-6dfd-11ea-821c-59bc24068207.png">
> 
> I am in favour of keeping the check-run details as concise as possible. Add any extra details to the logs.
> Title itself seems to contain average **`100`** characters. This would mean a limit of less than 600 CVEs (if we post "ID, Title") which seems pretty low.
> 
> @ammohant @ds-ms @shigupt202 - Thoughts?

Yes, let us restrict the checkrun output to be minimal in that case for now. Other way to address is to print the limit and said look at "..." for more.   But for now let us restrict it to ids only.

**Comment by ajinkya599** [comment]
Another question - What should we do in case we know that the text is going to cross the limit?
This we should think through before adding app integration.

Assuming this would not be a common scenario to whitelist so many vulnerabilities, I was thinking the following should be reasonable- 
1. Put as many vulnerabilities as we can, give the user an option to whitelist.
2. Once the user clicks on `add to whitelist`, the PR gets updated with that many vulnerabilities.
3. The check run is created again with the remaining vulnerabilities(as many as possible). This cycle can repeat.
