### ISSUE TITLE
Whitelist file path and naming.

### ISSUE THREAD

**Issue by ajinkya599** [shigupt202/local-container-scan#21]
It seems that other tools are keeping their configs in root folder under `.<toolname>` directory.
eg. `.circleci`, `.vscode`, `.dependabot`. 
- We should stick to this convention, i.e. `.containerscan` in root directory should contain the whitelist file.
- That said, should we think of a better name or `container scan` is good to go?

@pingvishal-msft @ammohant - thoughts?

**Comment by pingvishal** [comment]
.github folder is consistent with the other ci/cd tools. container scan runs as part of the workflows today and later might run async on the registry or automatically within the pipeline. .github/containerscan seems logical to me.
suggestion for whitelist file: .github/containerscan/whitelist.yaml
