### ISSUE TITLE
Check run improvements.

### ISSUE THREAD

**Issue by ajinkya599** [shigupt202/local-container-scan#7]
1. Make text in the check run more meaningful. Refer to the comments in pull request https://github.com/shigupt202/local-container-scan/pull/6
2. Review the texts used
--------------------------
<img width="428" alt="image" src="https://user-images.githubusercontent.com/11447401/77412209-91d6d200-6de3-11ea-8169-98a0b2620928.png">

--------------------------

3. Should we display the detailed error in case of failure while scanning, or its right place is only in logs?
--------------------------
<img width="973" alt="image" src="https://user-images.githubusercontent.com/11447401/77413471-67861400-6de5-11ea-9e97-396a70880a52.png">

--------------------------

**Comment by thesattiraju** [comment]
Add Vishal for reviewing points 1 and 2
